title: Blog       # Your blog's name
description: A blog about ML, algorithms, and big data. # Tagline
theme: minima              # Use GitHub's default theme
author:
  name: Omprakash Nain           # Dummy name (change later)
  email: b22ai062@iitj.ac.in  # Placeholder email