title: Dummy ML Blog       # Your blog's name
description: A blog about ML, algorithms, and big data. # Tagline
theme: minima              # Use GitHub's default theme
author:
  name: John Doe           # Dummy name (change later)
  email: john@example.com  # Placeholder email